name: celestia-daily # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
#version: '0.+git' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: celestia-qt

summary: Free, open source, Real-time 3D visualization of space. # 79 char long summary
description: |
  Celestia is a real-time space simulation which lets you experience the universe in three dimensions. Celestia does not confine you to the surface of the Earth, it allows you to travel throughout the solar system, to any of over 100,000 stars, or even beyond the galaxy. Travel in Celestia is seamless; the exponential zoom feature lets you explore space across a huge range of scales, from galaxy clusters down to spacecraft only a few meters across. A 'point-and-goto' interface makes it simple to navigate through the universe to the object you want to visit.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

architectures: #build Architectures
   - build-on: amd64 
   - build-on: i386
   - build-on: arm64
   
apps:
  celestia-qt:
    command: desktop-launch $SNAP/bin/run-celestia-qt.sh
    #desktop: $SNAP/usr/share/applications/celestia.desktop
    plugs: [desktop, wayland, x11, unity7, gsettings, opengl, network, network-bind, audio-playback, home, raw-usb]
    
layout:
  /usr/share/celestia:
    bind: $SNAP/usr/share/celestia
  #/usr/lib:
    #bind: $SNAP/usr/lib
    
parts:
  celestia-qt:
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      #- -DWITH_GTK_2_X = ON
      - -DENABLE_TTF=ON

    source: https://github.com/CelestiaProject/Celestia.git
    source-type: git
    #source-depth : 1
    #source-tag: 1.6.2
    

    after : [desktop-celestia]
    
    override-pull: |  
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | awk '{ gsub("_","."); print $1 }')"
      #Checkout that latest stable version
      last_committed_tag="$(git ls-remote --tags https://github.com/CelestiaProject/Celestia.git | awk ' !/v/ { print $2 }' | awk ' !/a/ { print $1 }' | sort -V | tail -n 1)"
      last_released_tag="$(snap info celestia-daily | awk '$1 == "beta:" { print $2 }')"
      #If the latest tag from the upstream project has not been released to
      #beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "${last_committed_tag} | awk '{ gsub("refs/tags/","v"); print $1 }'"
      fi    
    
    override-build: |
      snapcraftctl build
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      #cp ../src/debian/celestia-qt.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
      #mv $SNAPCRAFT_PART_INSTALL/usr/share/applications/celestia-qt.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/celestia.desktop
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      cp ../src/src/celestia/qt/data/celestia.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
    
    build-packages:
      - libepoxy-dev
      - libjpeg-dev
      - libpng-dev
      - libtheora-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libeigen3-dev
      - libfmt-dev
      - qtbase5-dev
      - qtbase5-dev-tools 
      - libqt5opengl5-dev
      - liblua5.3-dev
      - libfreetype6-dev
      
    stage-packages:
      - libepoxy0
      - libgl1
      - libgl1-mesa-glx
      - libglu1-mesa
      - liblua5.3-0
      - libogg0
      - libqt5opengl5
      - libtheora0
      - libcanberra-gtk3-module
      - gtk3-nocsd

  wrapper:
    plugin: dump
    after : [celestia-qt]
    override-pull: |
      snapcraftctl pull
      chmod +x $SNAPCRAFT_PART_SRC/run-celestia-qt.sh
    source: ./snap/local
    source-type: local
    organize:
      run-celestia-qt.sh: bin/run-celestia-qt.sh
      
      
  desktop-celestia:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    source-depth : 1
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
    - libgtk2.0-0
    
  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
